### ISSUE TITLE
undefined symbol: `kernel_context_options_set_validation_interface`

### ISSUE THREAD

**Issue by ismaelsadeeq** [stickies-v/py-bitcoinkernel#8]
Running this wrapper on the current main branch top commit `67463f3cb367fea2509041f64b8d0f704cdc9c54` results in the following failure:

```terminal
Traceback (most recent call last):
  File "/home/abubakar-dev/py-bitcoinkernel/block_parser/src/main.py", line 1, in <module>
    import pbk
  File "/home/abubakar-dev/py-bitcoinkernel/block_parser/.venv/lib/python3.10/site-packages/pbk/__init__.py", line 1, in <module>
    from pbk.block import Block, BlockHash, BlockIndex, BlockUndo
  File "/home/abubakar-dev/py-bitcoinkernel/block_parser/.venv/lib/python3.10/site-packages/pbk/block.py", line 4, in <module>
    import pbk.capi.bindings as k
  File "/home/abubakar-dev/py-bitcoinkernel/block_parser/.venv/lib/python3.10/site-packages/pbk/capi/__init__.py", line 1, in <module>
    from pbk.capi.base import KernelOpaquePtr, KernelPtr
  File "/home/abubakar-dev/py-bitcoinkernel/block_parser/.venv/lib/python3.10/site-packages/pbk/capi/base.py", line 3, in <module>
    import pbk.capi.bindings
  File "/home/abubakar-dev/py-bitcoinkernel/block_parser/.venv/lib/python3.10/site-packages/pbk/capi/bindings.py", line 527, in <module>
    kernel_context_options_set_validation_interface = BITCOINKERNEL_LIB.kernel_context_options_set_validation_interface
  File "/usr/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/local/lib/libbitcoinkernel.so: undefined symbol: kernel_context_options_set_validation_interface
```

After bisecting the code, I found that this failure does not occur in commit 59332f4d25554bc75fee87ce0e60c3f92b8d7e94
The issue seems to begin with commit 4103e2cb36b189fed5112b3461d7e673ee4b2533

**Comment by stickies-v** [comment]
This behaviour is loosely documented in the [README](https://github.com/stickies-v/py-bitcoinkernel?tab=readme-ov-file#libbitcoinkernel-shared-library):

> [!WARNING] While libbitcoinkernel and py-bitcoinkernel are in very early and experimental phases of development, no version management is done, and you must install the libbitcoinkernel version that is shipped with this library in depend/bitcoin/.

You need to install the bitcoinkernel version that is shipped in `depend/bitcoin/` (done automatically when installed with pip, if you remove the system-installed bitcoinkernel)

Perhaps it'd be useful to add some extra error handling when importing `pbk.capi.bindings` fails to report to the user that they probably have the wrong bitcoinkernel version installed.

**Comment by ismaelsadeeq** [comment]
> done automatically when installed with pip

The issue is when you have installed this library previously and are now updating, the auto installation will detect the previously installed `libbitcoinkernel` library and then won't install the one that comes with the library.

> Perhaps it'd be useful to add some extra error handling when importing pbk.capi.bindings fails to report to the user that they probably have the wrong bitcoinkernel version installed.

Prior to that at least recommending users to compile manually when updating the library is a good idea?
Something like https://github.com/ismaelsadeeq/py-bitcoinkernel/commit/130a0a06decb55f2aa12061849d713bde53aa012

**Comment by ismaelsadeeq** [comment]
I see that https://github.com/TheCharlatan/rust-bitcoinkernel seems to recompile aggressively after any update. While this can be redundant when there are no changes to the `libbitcoinkernel` library, but IMO it's better than the alternatives: 

1. Manually compiling 
2. Skipping compilation altogether (like `py-bitcoinkernel` does), which can lead to failures

Of course the best solution is recompiling only when the version on system is not the same with the one that comes with the library  :)

**Comment by stickies-v** [comment]
Sorry to keep this open for a while, I've been working on different approaches. With the recent advancements in compilation time (#7), I've updated the installation process and run-time library detection to no longer use system installed bitcoinkernel libraries (#17), and instead re-compile with every installation.

I think removing this footgun fully addressed this issue, but feel free to comment further if you have any more thoughts or follow-ups!

> Of course the best solution is recompiling only when the version on system is not the same with the one that comes with the library :)

We currently don't have the capability to do that. I've opened #11 and https://github.com/TheCharlatan/bitcoin/pull/23 to do that, but they're not really that important anymore after #17 .
